In [1]:
import vcf
import pandas as pd
import re

In [1]:
####### filter vcf file on our risk snps using vcftools in the Terminal ######
# command: vcftools --gzvcf ../Aetionomy/AETIO_CS_postimpvcf.gz --snps Final\ New\ Mappings\ /riskSnps_vcfinput.txt --recode --recode-INFO-all --out ../examples_with_vcftools/riskSNPs_only_subset.vcf

#done

In [9]:
#load cholesterol data, check ID consistency
dfs = pd.read_csv("../Aetionomy/cholesterolData_AETIONOMYPD.tsv", sep="\t")
Ids=list(dfs.index)
print (len(Ids)) #135 samples

135

In [10]:
vcf_reader = vcf.Reader(filename="../Aetionomy/riskSNPs_only.recode.vcf")
ids_vcf=sorted(vcf_reader.samples)
print (len(ids_vcf))

350

In [23]:
intersection=[x for x in Ids if x in ids_vcf]
len(intersection)

108

In [5]:
#working with vcf. SNPs to Patient
def SNPstoPatient(file):
    vcf_reader = vcf.Reader(filename=file)
    SNPtoPatientdic=dict()
    p = re.compile('AET[0-9]{4}')
    for record in vcf_reader:
        ID=record.ID
        if ID not in SNPtoPatientdic and ID!=None:
            SNPtoPatientdic[ID]=[]
            for call in record.samples:
                string_call=str(call)
                result = p.search(string_call)
                SNPtoPatientdic[ID].append(result.group(0))
    return SNPtoPatientdic

In [6]:
SNPs2Patient=SNPstoPatient("../Aetionomy/riskSNPs_only.recode.vcf")

In [34]:
for i in SNPs2Patient.keys():
    if len(SNPs2Patient[i])!=350:
        print (i)
        
print ("done") #all patients reveal all risk snps...

done

In [17]:
vcf_reader_test = vcf.Reader(filename='../Aetionomy/AETIO_CS_postimpvcf.gz')
vcf_reader_test.samples #not consistent with cholesterol ids!!

['AET0074',
 'AET0066',
 'AET0077',
 'AET0081',
 'AET0085',
 'AET0084',
 'AET0026',
 'AET0099',
 'AET0002',
 'AET0003',
 'AET0004',
 'AET0129',
 'AET0007',
 'AET0008',
 'AET0006',
 'AET0005',
 'AET0071',
 'AET0009',
 'AET0015',
 'AET0019',
 'AET0014',
 'AET0010',
 'AET0012',
 'AET0011',
 'AET0016',
 'AET0017',
 'AET0018',
 'AET0021',
 'AET0022',
 'AET0023',
 'AET0034',
 'AET0025',
 'AET0108',
 'AET0033',
 'AET0024',
 'AET0032',
 'AET0101',
 'AET0027',
 'AET0031',
 'AET0045',
 'AET0109',
 'AET0042',
 'AET0039',
 'AET0036',
 'AET0043',
 'AET0041',
 'AET0044',
 'AET0046',
 'AET0047',
 'AET0048',
 'AET0049',
 'AET0050',
 'AET0051',
 'AET0055',
 'AET0052',
 'AET0056',
 'AET0057',
 'AET0058',
 'AET0059',
 'AET0060',
 'AET0061',
 'AET0062',
 'AET0063',
 'AET0064',
 'AET0065',
 'AET0067',
 'AET0068',
 'AET0070',
 'AET0076',
 'AET0078',
 'AET0079',
 'AET0080',
 'AET0083',
 'AET0086',
 'AET0087',
 'AET0088',
 'AET0090',
 'AET0092',
 'AET0093',
 'AET0118',
 'AET0096',
 'AET0104',
 'AET0103',
 'AET0106',
 'AET0114',
 'AET0115',
 'AET0116',
 'AET0121',
 'AET0122',
 'AET0123',
 'AET0137',
 'AET0138',
 'AET0168',
 'AET0169',
 'AET0170',
 'AET0171',
 'AET0172',
 'AET0173',
 'AET0174',
 'AET0176',
 'AET0177',
 'AET0178',
 'AET0179',
 'AET0180',
 'AET0181',
 'AET0182',
 'AET0183',
 'AET0184',
 'AET0185',
 'AET0186',
 'AET0187',
 'AET0188',
 'AET0189',
 'AET0190',
 'AET0191',
 'AET0192',
 'AET0193',
 'AET0194',
 'AET0195',
 'AET0197',
 'AET0198',
 'AET0199',
 'AET0201',
 'AET0202',
 'AET0203',
 'AET0204',
 'AET0206',
 'AET0207',
 'AET0208',
 'AET0209',
 'AET0210',
 'AET0212',
 'AET0213',
 'AET0214',
 'AET0215',
 'AET0216',
 'AET0217',
 'AET0218',
 'AET0219',
 'AET0229',
 'AET0221',
 'AET0222',
 'AET0223',
 'AET0225',
 'AET0226',
 'AET0227',
 'AET0228',
 'AET0230',
 'AET0231',
 'AET0232',
 'AET0233',
 'AET0234',
 'AET0235',
 'AET0236',
 'AET0237',
 'AET0144',
 'AET0146',
 'AET0147',
 'AET0148',
 'AET0149',
 'AET0150',
 'AET0152',
 'AET0153',
 'AET0154',
 'AET0155',
 'AET0156',
 'AET0158',
 'AET0159',
 'AET0160',
 'AET0020',
 'AET0028',
 'AET0029',
 'AET0030',
 'AET0035',
 'AET0038',
 'AET0073',
 'AET0075',
 'AET0089',
 'AET0095',
 'AET0097',
 'AET0098',
 'AET0100',
 'AET0102',
 'AET0107',
 'AET0110',
 'AET0111',
 'AET0112',
 'AET0113',
 'AET0120',
 'AET0124',
 'AET0126',
 'AET0127',
 'AET0128',
 'AET0130',
 'AET0131',
 'AET0134',
 'AET0135',
 'AET0139',
 'AET0140',
 'AET0141',
 'AET0142',
 'AET0239',
 'AET0240',
 'AET0242',
 'AET0244',
 'AET0245',
 'AET0246',
 'AET0247',
 'AET0248',
 'AET0249',
 'AET0250',
 'AET0252',
 'AET0254',
 'AET0256',
 'AET0258',
 'AET0259',
 'AET0260',
 'AET0261',
 'AET0262',
 'AET0264',
 'AET0265',
 'AET0267',
 'AET0268',
 'AET0269',
 'AET0270',
 'AET0271',
 'AET0272',
 'AET0205',
 'AET0273',
 'AET0274',
 'AET0275',
 'AET0276',
 'AET0277',
 'AET0278',
 'AET0279',
 'AET0280',
 'AET0281',
 'AET0282',
 'AET0283',
 'AET0284',
 'AET0285',
 'AET0287',
 'AET0288',
 'AET0289',
 'AET0290',
 'AET0291',
 'AET0292',
 'AET0293',
 'AET0294',
 'AET0295',
 'AET0296',
 'AET0297',
 'AET0298',
 'AET0300',
 'AET0301',
 'AET0302',
 'AET0303',
 'AET0304',
 'AET0305',
 'AET0306',
 'AET0308',
 'AET0309',
 'AET0310',
 'AET0311',
 'AET0312',
 'AET0313',
 'AET0315',
 'AET0316',
 'AET0317',
 'AET0318',
 'AET0319',
 'AET0320',
 'AET0322',
 'AET0323',
 'AET0324',
 'AET0325',
 'AET0326',
 'AET0327',
 'AET0328',
 'AET0329',
 'AET0330',
 'AET0331',
 'AET0333',
 'AET0334',
 'AET0335',
 'AET0336',
 'AET0337',
 'AET0338',
 'AET0339',
 'AET0340',
 'AET0341',
 'AET0342',
 'AET0343',
 'AET0344',
 'AET0345',
 'AET0346',
 'AET0347',
 'AET0348',
 'AET0349',
 'AET0350',
 'AET0351',
 'AET0352',
 'AET0353',
 'AET0354',
 'AET0355',
 'AET0356',
 'AET0357',
 'AET0358',
 'AET0359',
 'AET0360',
 'AET0361',
 'AET0362',
 'AET0363',
 'AET0364',
 'AET0365',
 'AET0366',
 'AET0001',
 'AET0151',
 'AET0371',
 'AET0372',
 'AET0373',
 'AET0374',
 'AET0377',
 'AET0380',
 'AET0383',
 'AET0387',
 'AET0390',
 'AET0393',
 'AET0394',
 'AET0395',
 'AET0396',
 'AET0397',
 'AET0400',
 'AET0401',
 'AET0404',
 'AET0412',
 'AET0413',
 'AET0414',
 'AET0415',
 'AET0416',
 'AET0418',
 'AET0420',
 'AET0421',
 'AET0175',
 'AET0238',
 'AET0251',
 'AET0253',
 'AET0255',
 'AET0257',
 'AET0266']

In [ ]:
#waiting for the identifier mapping (AET) problem to be fixed

In [15]:
#load raw cholesterol data and snps
cholesterole = pd.read_csv("cholesterole_raw.csv")
snps = pd.read_csv("Final New Mappings /snps_genes_concatenated.csv")

In [8]:
#write risk snps to txt file for vcf filtering
snps_list=set(snps["rsID"].tolist())
with open("Final New Mappings /riskSnps_vcfinput.txt", "w") as text_file:
    for snp in snps_list:
        text_file.write(snp+"\n")

In [ ]:
#now run vcf filtering from terminal

In [23]:
#naive confounder dataframe

In [18]:
confounder=pd.read_csv("../Clinical_Data/AETIO_DIGPD_clinical_final.csv")
con_ids=confounder["AETID"].tolist()
print (len(con_ids))
print(len([x for x in vcf_reader_test.samples if x in con_ids])) #54 IDs missing

790
296

In [21]:
len([x for x in intersection if x in con_ids])

106

In [22]:
confounder

,AETID,Sex,Age_visit,Ethnicity,Smoking,Group,Cohort,DOB,date_of_visit,date_diag_pd,...,pdq39_tot,total_mds3_on,hy_stage,epworth,schwab,HADS_anxiety,HADS_depression,edu_level,coffee,alcohol
0,AET0001,male,43,Caucasian,ex,IPD,AETIO,15/02/1972,04/09/2015,15/01/2015,...,11.0,18.0,2.0,8.0,1.0,0.0,2.0,15.0,3.0,4.0
1,AET0002,male,67,Caucasian,never,IPD,AETIO,15/01/1948,11/09/2015,15/02/2013,...,55.0,19.0,2.0,3.0,2.0,10.0,7.0,18.0,1.0,2.0
2,AET0003,male,57,Caucasian,current,IPD,AETIO,15/03/1958,18/09/2015,15/04/2014,...,6.0,25.0,2.0,5.0,1.0,4.0,1.0,12.0,3.0,5.0
3,AET0004,male,61,Caucasian,never,IPD,AETIO,15/08/1954,25/09/2015,15/07/2012,...,42.0,26.0,2.0,18.0,2.0,9.0,7.0,16.0,3.0,5.0
4,AET0006,male,69,Caucasian,ex,IPD,AETIO,15/09/1946,05/11/2015,15/02/2013,...,24.0,18.0,2.0,1.0,2.0,4.0,1.0,12.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,AET1028,male,68,Caucasian,ex,IPD,DIGPD,04/12/1944,17/05/2013,01/05/2010,...,NaN,5.0,1.0,4.0,1.0,6.0,2.0,NaN,NaN,NaN
786,AET1029,female,65,Caucasian,never,IPD,DIGPD,26/02/1948,17/05/2013,01/11/2009,...,NaN,12.0,1.0,8.0,1.0,10.0,3.0,NaN,NaN,NaN
787,AET1030,male,42,Caucasian,current,IPD,DIGPD,05/05/1971,14/03/2013,01/10/2011,...,NaN,9.0,1.0,3.0,NaN,7.0,2.0,NaN,NaN,NaN
788,AET1031,female,53,North African/Arabic,never,IPD,DIGPD,08/07/1960,28/03/2013,01/02/2012,...,NaN,19.0,1.5,16.0,2.0,13.0,9.0,NaN,NaN,NaN
789,AET1032,female,65,Caucasian,never,IPD,DIGPD,10/02/1948,28/05/2013,01/07/2008,...,NaN,7.0,1.5,15.0,2.0,2.0,0.0,NaN,NaN,NaN

In [2]:
##naive model dataframe

In [9]:
cholesterole_snps=cholesterole.reindex(columns = cholesterole.columns.tolist() + list(set(snps["rsID"].tolist())))

In [10]:
cholesterole_snps

,AETID,Cholestanol,Lathosterol,Campesterol,Campestanol,Stigmasterol,Sitosterol,Sitostanol,Brassicasterol,Lanosterol,...,rs34046617,rs62210587,rs284648,rs9380339,rs142732024,rs33932778,rs35452111,rs10906925,rs13230910,rs11191575
0,AET1491,0.181095,0.227037,0.307736,3.069276,3.236899,0.151218,2.716353,26.045368,18.008165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AET1516,0.245600,0.242703,0.245851,3.415553,4.031518,0.133392,2.811780,20.195195,15.676148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AET1493,0.598218,0.339385,0.651776,5.865551,8.400074,0.303179,4.738678,44.809698,20.742546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AET1541,0.343007,0.094074,0.556650,5.495747,13.868731,0.351717,4.691476,25.151336,20.423470,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AET1580,0.170764,0.194446,0.096440,2.161297,1.457500,0.076421,2.547047,9.051412,15.081270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,AET1583,0.273462,1.033712,1.092019,6.058904,9.891930,0.552562,4.379954,51.575978,38.160554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,AET1757,0.314959,0.170382,0.224129,3.245831,5.987718,0.240201,3.340911,12.380979,18.711491,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,AET1726,0.408337,0.266054,0.365354,3.346033,4.724586,0.201519,3.746834,24.704809,17.870937,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,AET1742,0.415682,0.123021,0.303319,3.274349,4.214876,0.182739,3.160865,26.663208,16.202585,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,AET1748,0.381683,0.145697,0.325089,3.092097,5.030744,0.214579,3.005444,30.492859,12.327262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# mechanims model dataframe

In [11]:
#mechanisms
mechanisms=pd.read_csv('LordickData/neurommsig_pd_full_genes.csv')
MechanismToGene=mechanisms.to_dict("list")
#
#quickly remove nan values from gene lists to enhance efficiency
def remove_float_from_list(the_list):
    return [value for value in the_list if type(value)!=float]
#
MechanismToGene_noNans={x:remove_float_from_list(y) for x,y in MechanismToGene.items()}

In [13]:
mechanisms_only=list(MechanismToGene_noNans.keys())

In [14]:
cholesterole_mechanisms=cholesterole.reindex(columns = cholesterole.columns.tolist() + mechanisms_only)

In [15]:
cholesterole_mechanisms

,AETID,Cholestanol,Lathosterol,Campesterol,Campestanol,Stigmasterol,Sitosterol,Sitostanol,Brassicasterol,Lanosterol,...,Matrix metalloproteinase subgraph,RhoA subgraph,Bcl-2 subgraph,Mitochondria fusion subgraph,Unfolded protein response subgraph,Vascular endothelial growth factor subgraph,Amyloidogenic subgraph,Toll like receptor subgraph,Estrogen subgraph,Cyclic AMP subgraph
0,AET1491,0.181095,0.227037,0.307736,3.069276,3.236899,0.151218,2.716353,26.045368,18.008165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AET1516,0.245600,0.242703,0.245851,3.415553,4.031518,0.133392,2.811780,20.195195,15.676148,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AET1493,0.598218,0.339385,0.651776,5.865551,8.400074,0.303179,4.738678,44.809698,20.742546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AET1541,0.343007,0.094074,0.556650,5.495747,13.868731,0.351717,4.691476,25.151336,20.423470,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AET1580,0.170764,0.194446,0.096440,2.161297,1.457500,0.076421,2.547047,9.051412,15.081270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,AET1583,0.273462,1.033712,1.092019,6.058904,9.891930,0.552562,4.379954,51.575978,38.160554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,AET1757,0.314959,0.170382,0.224129,3.245831,5.987718,0.240201,3.340911,12.380979,18.711491,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,AET1726,0.408337,0.266054,0.365354,3.346033,4.724586,0.201519,3.746834,24.704809,17.870937,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,AET1742,0.415682,0.123021,0.303319,3.274349,4.214876,0.182739,3.160865,26.663208,16.202585,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,AET1748,0.381683,0.145697,0.325089,3.092097,5.030744,0.214579,3.005444,30.492859,12.327262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#########################################################